apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-stable
  labels:
    app: backend
    track: stable
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
      track: stable
  template:
    metadata:
      labels:
        app: backend
        track: stable
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: NODE_ENV
          value: "production"
